// cmd_data.js — the NetHack extended-command table (cmd.c extcmdlist[]).
// Each entry: { key, txt, desc, flags } where 'key' is the default key binding
// (a char code, or null for commands with no default key), 'txt' the extended
// command name (#txt), 'desc' its one-line description, and 'flags' the raw C
// flag expression (used to filter AUTOCOMPLETE / WIZMODECMD / etc.).  Order
// matches C so windowport indices are stable.  Build-constant.
//
// C ref: src/cmd.c extcmdlist[].
export const EXTCMD_TABLE = [
    { key: 35, txt: "#", desc: "enter and perform an extended command", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 191, txt: "?", desc: "list all extended commands", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD | CMD_M_PREFIX" },
    { key: 225, txt: "adjust", desc: "adjust inventory letters", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 193, txt: "annotate", desc: "name current level", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD | CMD_M_PREFIX" },
    { key: 97, txt: "apply", desc: "apply (use) a tool (pick-axe, key, lamp...)", flags: "CMD_M_PREFIX" },
    { key: 24, txt: "attributes", desc: "show your attributes", flags: "IFBURIED | GENERALCMD" },
    { key: 64, txt: "autopickup", desc: "toggle the 'autopickup' option on/off", flags: "IFBURIED | GENERALCMD" },
    { key: 0, txt: "bugreport", desc: "file a bug report", flags: "GENERALCMD | NOFUZZERCMD" },
    { key: 67, txt: "call", desc: "name a monster, specific object, or type of object", flags: "IFBURIED | GENERALCMD" },
    { key: 90, txt: "cast", desc: "zap (cast) a spell", flags: "IFBURIED" },
    { key: 227, txt: "chat", desc: "talk to someone", flags: "IFBURIED | AUTOCOMPLETE" },
    { key: 118, txt: "chronicle", desc: "show journal of major events", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 99, txt: "close", desc: "close a door", flags: "0" },
    { key: 195, txt: "conduct", desc: "list voluntary challenges you have maintained", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 0, txt: "debugfuzzer", desc: "start the fuzz tester", flags: "IFBURIED | WIZMODECMD | NOFUZZERCMD" },
    { key: 228, txt: "dip", desc: "dip an object into something", flags: "AUTOCOMPLETE | CMD_M_PREFIX" },
    { key: 62, txt: "down", desc: "go down a staircase", flags: "CMD_M_PREFIX" },
    { key: 100, txt: "drop", desc: "drop an item", flags: "0" },
    { key: 68, txt: "droptype", desc: "drop specific item types", flags: "0" },
    { key: 101, txt: "eat", desc: "eat something", flags: "CMD_M_PREFIX" },
    { key: 69, txt: "engrave", desc: "engrave writing on the floor", flags: "0" },
    { key: 229, txt: "enhance", desc: "advance or check weapon and spell skills", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 216, txt: "exploremode", desc: "enter explore (discovery) mode", flags: "IFBURIED | GENERALCMD | NOFUZZERCMD" },
    { key: 70, txt: "fight", desc: "prefix: force fight even if you don't see a monster", flags: "PREFIXCMD" },
    { key: 102, txt: "fire", desc: "fire ammunition from quiver", flags: "0" },
    { key: 230, txt: "force", desc: "force a lock", flags: "AUTOCOMPLETE" },
    { key: 231, txt: "genocided", desc: "list monsters that have been genocided or become extinct", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD | CMD_M_PREFIX" },
    { key: 59, txt: "glance", desc: "show what type of thing a map symbol corresponds to", flags: "IFBURIED | GENERALCMD" },
    { key: 63, txt: "help", desc: "give a help message", flags: "IFBURIED | GENERALCMD" },
    { key: 0, txt: "herecmdmenu", desc: "show menu of commands you can do here", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 0, txt: "history", desc: "show a summary of the game's development", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 105, txt: "inventory", desc: "show your inventory", flags: "IFBURIED | GENERALCMD" },
    { key: 73, txt: "inventtype", desc: "show inventory of one specific item class", flags: "IFBURIED | GENERALCMD" },
    { key: 233, txt: "invoke", desc: "invoke an object's special powers", flags: "IFBURIED | AUTOCOMPLETE" },
    { key: 234, txt: "jump", desc: "jump to another location", flags: "AUTOCOMPLETE" },
    { key: 4, txt: "kick", desc: "kick something", flags: "0" },
    { key: 92, txt: "known", desc: "show what object types have been discovered", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 96, txt: "knownclass", desc: "show discovered types for one class of objects", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 0, txt: "levelchange", desc: "change experience level", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "lightsources", desc: "show mobile light sources", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 58, txt: "look", desc: "look at what is here", flags: "IFBURIED" },
    { key: 0, txt: "lookaround", desc: "describe what you can see", flags: "IFBURIED | GENERALCMD" },
    { key: 236, txt: "loot", desc: "loot a box on the floor", flags: "AUTOCOMPLETE | CMD_M_PREFIX" },
    { key: 0, txt: "migratemons", desc: "show migrating monsters", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 237, txt: "monster", desc: "use monster's special ability", flags: "IFBURIED | AUTOCOMPLETE" },
    { key: 238, txt: "name", desc: "same as call; name a monster or object or object type", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 239, txt: "offer", desc: "offer a sacrifice to the gods", flags: "AUTOCOMPLETE | CMD_M_PREFIX" },
    { key: 111, txt: "open", desc: "open a door", flags: "0" },
    { key: 79, txt: "options", desc: "show option settings", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 0, txt: "optionsfull", desc: "show all option settings, possibly change them", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 15, txt: "overview", desc: "show a summary of the explored dungeon", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD | CMD_M_PREFIX" },
    { key: 0, txt: "panic", desc: "test panic routine (fatal to game)", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 112, txt: "pay", desc: "pay your shopping bill", flags: "CMD_M_PREFIX" },
    { key: 124, txt: "perminv", desc: "scroll persistent inventory display", flags: "IFBURIED | GENERALCMD | NOFUZZERCMD" },
    { key: 44, txt: "pickup", desc: "pick up things at the current location", flags: "CMD_M_PREFIX" },
    { key: 0, txt: "polyself", desc: "polymorph self", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 240, txt: "pray", desc: "pray to the gods for help", flags: "IFBURIED | AUTOCOMPLETE" },
    { key: 16, txt: "prevmsg", desc: "view recent game messages", flags: "IFBURIED | GENERALCMD | CMD_INSANE" },
    { key: 80, txt: "puton", desc: "put on an accessory (ring, amulet, etc)", flags: "0" },
    { key: 113, txt: "quaff", desc: "quaff (drink) something", flags: "CMD_M_PREFIX" },
    { key: 0, txt: "quit", desc: "exit without saving current game", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD | NOFUZZERCMD" },
    { key: 81, txt: "quiver", desc: "select ammunition for quiver", flags: "0" },
    { key: 114, txt: "read", desc: "read a scroll or spellbook", flags: "0" },
    { key: 18, txt: "redraw", desc: "redraw screen", flags: "IFBURIED | GENERALCMD | CMD_INSANE" },
    { key: 82, txt: "remove", desc: "remove an accessory (ring, amulet, etc)", flags: "0" },
    { key: 1, txt: "repeat", desc: "repeat a previous command", flags: "IFBURIED | GENERALCMD" },
    { key: 109, txt: "reqmenu", desc: "prefix: request menu or modify command", flags: "PREFIXCMD" },
    { key: 31, txt: "retravel", desc: "travel to previously selected travel location", flags: "0" },
    { key: 210, txt: "ride", desc: "mount or dismount a saddled steed", flags: "AUTOCOMPLETE" },
    { key: 242, txt: "rub", desc: "rub a lamp or a stone", flags: "AUTOCOMPLETE" },
    { key: 71, txt: "run", desc: "prefix: run until something interesting is seen", flags: "PREFIXCMD" },
    { key: 103, txt: "rush", desc: "prefix: rush until something interesting is seen", flags: "PREFIXCMD" },
    { key: 83, txt: "save", desc: "save the game and exit", flags: "IFBURIED | GENERALCMD | NOFUZZERCMD" },
    { key: 0, txt: "saveoptions", desc: "save the game configuration", flags: "IFBURIED | GENERALCMD | NOFUZZERCMD" },
    { key: 115, txt: "search", desc: "search for traps and secret doors", flags: "IFBURIED | CMD_M_PREFIX" },
    { key: 42, txt: "seeall", desc: "show all equipment in use", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 34, txt: "seeamulet", desc: "show the amulet currently worn", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 91, txt: "seearmor", desc: "show the armor currently worn", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 61, txt: "seerings", desc: "show the ring(s) currently worn", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 40, txt: "seetools", desc: "show the tools currently in use", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 41, txt: "seeweapon", desc: "show the weapon currently wielded", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 33, txt: "shell", desc: "leave game to enter a sub-shell ('exit' to come back)", flags: "(IFBURIED | GENERALCMD | NOFUZZERCMD\n                        | CMD_NOT_AVAILABLE\n                        )" },
    { key: 36, txt: "showgold", desc: "show gold, possibly shop credit or debt", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 43, txt: "showspells", desc: "list and reorder known spells", flags: "IFBURIED | GENERALCMD" },
    { key: 94, txt: "showtrap", desc: "describe an adjacent, discovered trap", flags: "IFBURIED | GENERALCMD" },
    { key: 243, txt: "sit", desc: "sit down", flags: "AUTOCOMPLETE" },
    { key: 0, txt: "stats", desc: "show memory statistics", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 26, txt: "suspend", desc: "push game to background ('fg' to come back)", flags: "(IFBURIED | GENERALCMD | NOFUZZERCMD\n                               | CMD_NOT_AVAILABLE\n                               )" },
    { key: 120, txt: "swap", desc: "swap wielded and secondary weapons", flags: "0" },
    { key: 84, txt: "takeoff", desc: "take off one piece of armor", flags: "0" },
    { key: 65, txt: "takeoffall", desc: "remove all armor", flags: "0" },
    { key: 20, txt: "teleport", desc: "teleport around the level", flags: "IFBURIED | CMD_M_PREFIX" },
    { key: 127, txt: "terrain", desc: "view map without monsters or objects obstructing it", flags: "IFBURIED | GENERALCMD | AUTOCOMPLETE" },
    { key: 0, txt: "therecmdmenu", desc: "menu of commands you can do from here to adjacent spot", flags: "AUTOCOMPLETE | GENERALCMD | MOUSECMD" },
    { key: 116, txt: "throw", desc: "throw something", flags: "0" },
    { key: 0, txt: "timeout", desc: "look at timeout queue and hero's timed intrinsics", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 212, txt: "tip", desc: "empty a container", flags: "AUTOCOMPLETE | CMD_M_PREFIX" },
    { key: 0, txt: "toggle", desc: "toggle boolean option", flags: "IFBURIED | GENERALCMD | CMD_PARAM" },
    { key: 95, txt: "travel", desc: "travel to a specific location on the map", flags: "CMD_M_PREFIX" },
    { key: 244, txt: "turn", desc: "turn undead away", flags: "IFBURIED | AUTOCOMPLETE" },
    { key: 88, txt: "twoweapon", desc: "toggle two-weapon combat", flags: "0" },
    { key: 245, txt: "untrap", desc: "untrap something", flags: "AUTOCOMPLETE" },
    { key: 60, txt: "up", desc: "go up a staircase", flags: "CMD_M_PREFIX" },
    { key: 214, txt: "vanquished", desc: "list vanquished monsters", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD | CMD_M_PREFIX" },
    { key: 246, txt: "version", desc: "list compile time options for this version of NetHack", flags: "IFBURIED | AUTOCOMPLETE | GENERALCMD" },
    { key: 86, txt: "versionshort", desc: "show version and date+time program was built", flags: "IFBURIED | GENERALCMD | CMD_M_PREFIX" },
    { key: 0, txt: "vision", desc: "show vision array", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 46, txt: "wait", desc: "rest one move while doing nothing", flags: "IFBURIED | CMD_M_PREFIX" },
    { key: 87, txt: "wear", desc: "wear a piece of armor", flags: "0" },
    { key: 38, txt: "whatdoes", desc: "tell what a command does", flags: "IFBURIED | GENERALCMD" },
    { key: 47, txt: "whatis", desc: "show what type of thing a symbol corresponds to", flags: "IFBURIED | GENERALCMD" },
    { key: 119, txt: "wield", desc: "wield (put in use) a weapon", flags: "0" },
    { key: 247, txt: "wipe", desc: "wipe off your face", flags: "AUTOCOMPLETE" },
    { key: 0, txt: "wizborn", desc: "show stats of monsters created", flags: "IFBURIED | WIZMODECMD" },
    { key: 0, txt: "wizbury", desc: "bury objs under and around you", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizcast", desc: "cast any spell", flags: "IFBURIED | WIZMODECMD" },
    { key: 0, txt: "wizcustom", desc: "show customized glyphs", flags: "IFBURIED | WIZMODECMD | NOFUZZERCMD" },
    { key: 5, txt: "wizdetect", desc: "reveal hidden things within a small radius", flags: "IFBURIED | WIZMODECMD" },
    { key: 0, txt: "wizdispmacros", desc: "validate the display macro ranges", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizfliplevel", desc: "flip the level", flags: "IFBURIED | WIZMODECMD" },
    { key: 7, txt: "wizgenesis", desc: "create a monster", flags: "IFBURIED | WIZMODECMD" },
    { key: 9, txt: "wizidentify", desc: "identify all items in inventory", flags: "IFBURIED | WIZMODECMD" },
    { key: 0, txt: "wizintrinsic", desc: "set an intrinsic", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizkill", desc: "slay a monster", flags: "(IFBURIED | AUTOCOMPLETE | WIZMODECMD\n                         | CMD_M_PREFIX | NOFUZZERCMD)" },
    { key: 22, txt: "wizlevelport", desc: "teleport to another level", flags: "IFBURIED | WIZMODECMD | CMD_M_PREFIX" },
    { key: 0, txt: "wizloaddes", desc: "load and execute a des-file lua script", flags: "IFBURIED | WIZMODECMD | NOFUZZERCMD" },
    { key: 0, txt: "wizloadlua", desc: "load and execute a lua script", flags: "IFBURIED | WIZMODECMD | NOFUZZERCMD" },
    { key: 0, txt: "wizobjprobs", desc: "list object generation probabilities", flags: "IFBURIED | WIZMODECMD" },
    { key: 0, txt: "wizmakemap", desc: "recreate the current level", flags: "IFBURIED | WIZMODECMD" },
    { key: 6, txt: "wizmap", desc: "map the level", flags: "IFBURIED | WIZMODECMD" },
    { key: 0, txt: "wizmondiff", desc: "validate the difficulty ratings of monsters", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizrumorcheck", desc: "verify rumor boundaries", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizseenv", desc: "show map locations' seen vectors", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizshownhuuid", desc: "show NHUUID for this game", flags: "AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizsmell", desc: "smell monster", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wiztelekinesis", desc: "telekinesis", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 0, txt: "wizwhere", desc: "show locations of special levels", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 23, txt: "wizwish", desc: "wish for something", flags: "IFBURIED | CMD_M_PREFIX | WIZMODECMD" },
    { key: 0, txt: "wmode", desc: "show wall modes", flags: "IFBURIED | AUTOCOMPLETE | WIZMODECMD" },
    { key: 122, txt: "zap", desc: "zap a wand", flags: "0" },
    { key: 0, txt: "movewest", desc: "move west (screen left)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "movenorthwest", desc: "move northwest (screen upper left)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "movenorth", desc: "move north (screen up)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "movenortheast", desc: "move northeast (screen upper right)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "moveeast", desc: "move east (screen right)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "movesoutheast", desc: "move southeast (screen lower right)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "movesouth", desc: "move south (screen down)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "movesouthwest", desc: "move southwest (screen lower left)", flags: "MOVEMENTCMD | CMD_MOVE_PREFIXES" },
    { key: 0, txt: "rushwest", desc: "rush west (screen left)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "rushnorthwest", desc: "rush northwest (screen upper left)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "rushnorth", desc: "rush north (screen up)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "rushnortheast", desc: "rush northeast (screen upper right)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "rusheast", desc: "rush east (screen right)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "rushsoutheast", desc: "rush southeast (screen lower right)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "rushsouth", desc: "rush south (screen down)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "rushsouthwest", desc: "rush southwest (screen lower left)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runwest", desc: "run west (screen left)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runnorthwest", desc: "run northwest (screen upper left)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runnorth", desc: "run north (screen up)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runnortheast", desc: "run northeast (screen upper right)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runeast", desc: "run east (screen right)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runsoutheast", desc: "run southeast (screen lower right)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runsouth", desc: "run south (screen down)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "runsouthwest", desc: "run southwest (screen lower left)", flags: "MOVEMENTCMD | CMD_M_PREFIX" },
    { key: 0, txt: "clicklook", desc: "", flags: "INTERNALCMD | MOUSECMD" },
    { key: 0, txt: "mouseaction", desc: "", flags: "INTERNALCMD | MOUSECMD" },
    { key: 0, txt: "altadjust", desc: "", flags: "INTERNALCMD" },
    { key: 0, txt: "altdip", desc: "", flags: "INTERNALCMD" },
    { key: 0, txt: "alttakeoff", desc: "", flags: "INTERNALCMD" },
    { key: 0, txt: "altunwield", desc: "", flags: "INTERNALCMD" },
];
