// C ref: dat/quest.lua questtext[section][msgid].synopsis — the one-line summary
// questpgr.c com_pager_core() hands to putmsghistory() for ^P recall.
// Generated from the lua table; %-codes are resolved at delivery time.
export const QUEST_SYNOPSIS = {
    Arc: {
        assignquest: "[%nC has stolen %o.  Locate %i, defeat %ni, and return %O.]",
        badalign: "[\"%pC, you have strayed from the %a path.  Purify yourself!\"]",
        badlevel: "[%pC, a mere %r is too inexperienced.]",
        firsttime: "[You arrive at %H, but all is not well.]",
        goal_first: "[This strange feeling must be the presence of %o.]",
        gotit: "[The power of %o flows through your body!  You must return it to %l.]",
        hasamulet: "[Take the Amulet to the Astral Plane and sacrifice it at the altar of %d.]",
        leader_first: "[\"You have returned, %p, to a difficult task.\"]",
        leader_last: "[\"%pC, you have failed us.  Begone!\"]",
        locate_first: "[This foreboding edifice must hide the entrance to %i.]",
        nemesis_first: "[\"Come, %p, I shall destroy you!\"]",
        nemesis_next: "[\"Again you try to best me, %p?  You shall never recover %o.\"]",
        offeredit: "[%lC instructs you to guard %o from now on.]",
        offeredit2: "[\"Resume your search for the Amulet beyond the magic portal to %Z.\"]",
        posthanks: "[\"Have you progressed with your quest to regain the Amulet of Yendor for %d?\"]",
    },
    Bar: {
        assignquest: "[\"Find %n, defeat %ni, and return %o to us.\"]",
        badalign: "[\"You have wandered from the path of the %a.  Come back when you have atoned.\"]",
        badlevel: "[\"You are too inexperienced.  Come back when you are %Ra.\"]",
        firsttime: "[You reach the vicinity of %H, but sense evil magic nearby.]",
        goal_first: "[This is surely the lair of %n.]",
        gotit: "[You feel the power of %o flowing through your hands.]",
        hasamulet: "[\"Take the Amulet to the altar of %d on the Astral Plane and offer it.\"]",
        killed_nemesis: "[%nC curses you, but you feel the overpowering aura of magic fading.]",
        leader_first: "[\"At last you have returned.  There is a great quest you must undertake.\"]",
        leader_last: "[\"You have betrayed %d; soon %n will destroy us.  Begone!\"]",
        locate_first: "[You have located %i.]",
        nemesis_first: "[%nC boasts that %nh has slain many.  \"Prepare to die, %c.\"]",
        offeredit: "[%lC tells you to guard %o, and to return when you have triumphed.]",
        offeredit2: "[\"You keep %o.  Return to %Z to search for the Amulet.\"]",
    },
    Cav: {
        assignquest: "[Find and defeat %n, recover %o, and return with it.]",
        badalign: "[\"You no longer follow the path of the %a.  Go, and purify yourself.\"]",
        badlevel: "[\"%rA is too inexperienced.  Come back when you have progressed.\"]",
        firsttime: "[You arrive back at %H, but something is wrong here.]",
        goal_first: "[You enter a large cavern.  %nC is present.]",
        gotit: "[%oC fills you with a feeling of power.]",
        hasamulet: "[\"Take the Amulet to the altar of %d on the Astral Plane and offer it.\"]",
        leader_first: "[\"You have returned.  We are in dire need of your help.\"]",
        leader_last: "[\"You have betrayed the %L.  Begone!\"]",
        locate_first: "[You %x many large claw marks, smell carrion, and notice bones.]",
        nemesis_first: "[%nC threatens to eat you.]",
        offeredit: "[\"Take %o with you.  It will help in your quest for the Amulet of Yendor.\"]",
        offeredit2: "[\"You are the keeper of %o now.  Return to %Z to search for the Amulet.]",
    },
    Hea: {
        assignquest: "[Travel to %i on your way to recover %o from %n.]",
        badalign: "[Return when you are more %a.]",
        badlevel: "[You are too inexperienced.  Return when you are %Ra.]",
        firsttime: "[You arrive back at %H and must find %l.]",
        goal_first: "[You have reached the lair of %n.  Take %o away from %ni.]",
        gotit: "[You feel the healing power of %o and should return it to %l.]",
        hasamulet: "[\"You have recovered the Amulet.  Travel to the Astral Plane and return it to %d.\"]",
        killed_nemesis: "[%nC curses you as %nh dies.]",
        leader_first: "[%l is weak from the struggle with %n.  %lH wants to examine you.]",
        leader_last: "[You are a failure as a healer.]",
        locate_first: "[You have reached %i but all is not well.]",
        nemesis_first: "[\"I will take your life, then defeat %l.\"]",
        offeredit: "[%l touches %o and tells %lj %gP to do so too, then tells you to take it with you.]",
        offeredit2: "[%l tells you to keep %o and return to %Z to search for the Amulet.]",
    },
    Kni: {
        assignquest: "[Pass through %i to reach %n.  Destroy %ni and return with %o.]",
        badalign: "[Go and do penance.  Return when you are truly %a.]",
        badlevel: "[You are not prepared to face %n.  Return when you are %Ra.]",
        firsttime: "[Signs of battle include long gouges in the walls of %H.]",
        goal_first: "[You %x the entrance to a cavern inside a hill.]",
        gotit: "[You feel the magic of %o.]",
        hasamulet: "[Take the Amulet to the Astral Plane and deliver it to %d.]",
        killed_nemesis: "[%nC curses you as %nh dies.]",
        leader_first: "[%lC checks whether you are ready for a great undertaking.]",
        leader_last: "[You are a disgrace as %ca.]",
        locate_first: "[You have reached %i and can %x a shrine.]",
        nemesis_first: "[%nC taunts you and issues a threat against %H.]",
        offeredit: "[%oC is yours now.  It will aid in your search for the Amulet.]",
        offeredit2: "[You are the keeper of %o.  Return to %Z and find the Amulet.]",
    },
    Mon: {
        assignquest: "[Find %i, then continue to %ns lair.  Defeat %ni and return with %o.]",
        badalign: "[You must atone.  Come back when you are worthy of %d.]",
        badlevel: "[You are not ready to face %n.  Come back when you are %Ra.]",
        firsttime: "[You have reached %H but something is wrong.  %lC needs your aid.]",
        goal_first: "[You are surrounded by brimstone, lava, and elementals.]",
        gotit: "[You feel the essence of %d and realize that you should take %o to %l.]",
        hasamulet: "[Take the Amulet to the Astral Plane and deliver it to %d.]",
        killed_nemesis: "[As %n dies, %nh threatens to return.]",
        leader_first: "[%lC checks whether you are ready for the great challenge.]",
        leader_last: "[You are a heretic and have failed utterly.]",
        locate_first: "[You have reached %i.  %nC lurks further ahead.]",
        nemesis_first: "[You are no %g.  You shall never regain %o.]",
        offeredit: "[Keep %o.  %oH will help you recover the Amulet of Yendor.]",
        offeredit2: "[Keep %o and return to %Z to search for the Amulet.]",
    },
    Pri: {
        assignquest: "[%nC invaded %H and captured %o.  Defeat %ni and retrieve %oh.]",
        badalign: "[You have deviated from the path.  Return when you have purified yourself.]",
        badlevel: "[%rA cannot withstand %n.  Come back when you are %Ra.]",
        firsttime: "[You are at %H; the doors are closed.  %lC needs your help!]",
        goal_first: "[The stench of brimstone surrounds you, the shrieks and moans are endless.]",
        gotit: "[You feel %d as you pick up %o; return %oh to %l.]",
        hasamulet: "[Take the Amulet to the Astral Plane and offer it on %ds altar.]",
        killed_nemesis: "[%nC dies.  Moloch is aware of you and angry at %n.]",
        leader_first: "[You have returned and we need your help.  Are you ready?]",
        leader_last: "[You are a heretic who has deviated from the teachings of %d.]",
        locate_first: "[You have found %i.  The trail to %n lies ahead.]",
        nemesis_first: "[%lC has sent you, but you are no %gC.  I shall destroy you.]",
        offeredit: "[Congratulations, %p.  Keep %o; go and recover the Amulet.]",
        offeredit2: "[%oC is yours now.  Return to %Z and find the Amulet.]",
    },
    Ran: {
        assignquest: "[%nC has stolen %o.  Infiltrate %i and retrieve %oh for us.]",
        badalign: "[You are not sufficiently %a.  Come back when you have purified yourself.]",
        badlevel: "[You are too inexperienced.  Come back when you are %Ra.]",
        firsttime: "[The ancient forest grove is surrounded by centaurs.]",
        goal_first: "[You descend into a subterranean complex.  Hooves clatter in the distance.]",
        gotit: "[You pick up %o and feel power.  It's time to return %oh to %l.]",
        hasamulet: "[You have the Amulet!  Take it to the Astral Plane and offer it to %d.]",
        killed_nemesis: "[%nC curses you as %nh dies.]",
        leader_first: "[You have returned, %p.  We need your help.  Are you ready?]",
        leader_last: "[You are not sufficiently %a.  We renounce your %shood.]",
        locate_first: "[This is %i.  There are bats nearby.  Beware the wumpus!]",
        locate_next: "[You are in %i.  There are pits.  There are bats nearby.]",
        nemesis_first: "[You have come to recover %o, but I shall keep %oh and you shall die.]",
        offeredit: "[You have succeeded.  Take %o with you as you go to find the Amulet.]",
        offeredit2: "[You are the keeper of %o now.  Go and find the Amulet.]",
    },
    Rog: {
        assignquest: "[Get %o from %n and bring it to %l.]",
        badalign: "[Come back when you are really %a.]",
        badlevel: "[%rA is not adequately trained to handle this job.]",
        firsttime: "[You are in Ransmannsby, where you trained.  Find %l.]",
        goal_first: "[You sense %o.]",
        gotit: "[You pick up %o and know that %l should not have it.]",
        hasamulet: "[Take the Amulet to the Astral Plane and find %ds temple.]",
        killed_nemesis: "[Before dying, %n tells you to use the %o wisely.]",
        leader_first: "[You owe back dues to your guild.  You can pay them off if you're up to the job.]",
        leader_last: "[You must go.]",
        leader_next: "[Are you stupid or are you ready?]",
        nemesis_other: "[You cannot trust %l.]",
        nemesis_wantsit: "[%lC should not have %o.]",
        offeredit: "[Take %o with you and go.]",
        offeredit2: "[Take %o and acquire the Amulet.]",
        posthanks: "[How about trading %o for something?]",
    },
    Sam: {
        assignquest: "[You must enter %i, then regain %o from %n.]",
        badalign: "[When you can think %a and act %a then return.]",
        badlevel: "[\"I require %Ra to defeat %n.  Return when you are ready.\"]",
        firsttime: "[The banner of %n flies above town.  What has happened to %l?]",
        goal_first: "[You feel the taunts %n, but after offering a prayer to %d, you proceed.]",
        gotit: "[You feel the power of %o and are humbled.]",
        hasamulet: "[Take the Amulet to the Astral Plane to finish your task.]",
        killed_nemesis: "[%nC dies without honor.]",
        leader_first: "[%lC needs someone to lead %lj samurai against %n.  Are you ready?]",
        leader_last: "[Leave and do not come back.]",
        leader_other: "[Are you truly a samurai?]",
        offeredit: "[The emperor wants you to take %o and recover the Amulet.]",
        offeredit2: "[Take %o, return to %Z, and recover the Amulet.]",
        othertime: "[%HC is threatened by %n.]",
    },
    Tou: {
        assignquest: "[Enter %i and recover %o from %n.]",
        badalign: "[You are not sufficiently %a.  Return when you are.]",
        badlevel: "[Return when you are %Ra.]",
        firsttime: "[You find yourself back at %H, but the quiet is ominous.]",
        gotit: "[You pick up %o and feel relief.  Return it to %l.]",
        hasamulet: "[You have the Amulet.  Take it to the Astral Plane to finish your task.]",
        killed_nemesis: "[%nC curses at you as %nh dies.]",
        leader_first: "[Someone must defeat %n.  Are your ready?]",
        leader_last: "[Leave %H and never return.]",
        locate_first: "[You %x the handiwork of %ns henchlings.]",
        nemesis_first: "[%rA will not defeat me.]",
        nemesis_other: "[Run away or you will suffer severely.]",
        nemesis_wantsit: "[\"Return %o to me and we will rule %H.\"]",
        offeredit: "[Take %o and with %ds guidance, recover the Amulet.]",
        offeredit2: "[Keep %o and return to %Z through the portal.]",
    },
    Val: {
        assignquest: "[Find %i; defeat %n; return with %o.]",
        badalign: "[You have strayed from the %a path.  Return after you purify yourself.]",
        badlevel: "[Come back when you are %Ra.]",
        firsttime: "[You arrive below %H.  Something is wrong; there is lava present.]",
        goal_first: "[This is the lair of %n.]",
        gotit: "[You must return %o to %l.]",
        hasamulet: "[Take the Amulet to %ds temple on the Astral Plane and offer it.]",
        killed_nemesis: "[%nC dies.]",
        leader_first: "[We need your aid.  Are you ready?]",
        leader_last: "[\"Begone from my presence and never return.\"]",
        locate_first: "[This is the entrance to %i.]",
        nemesis_first: "[\"%oC has shown me that I must kill you.\"]",
        offeredit: "[Take %o.  Search for the Amulet.]",
        offeredit2: "[You are %os keeper now.  Return through the portal and find the Amulet.]",
    },
    Wiz: {
        assignquest: "[Travel to %i; overcome %n; return with %o.]",
        badalign: "[Go; come back when you are worthy of %d.]",
        badlevel: "[Go; return when you are %Ra.]",
        firsttime: "[You have arrived at %ls tower but something is very wrong.]",
        gotit: "[You feel %os power and know you should return %oh to %l.]",
        hasamulet: "[Take the Amulet to %ds altar on the Astral Plane.]",
        killed_nemesis: "[%nC curses you as %nh dies.]",
        leader_first: "[You have come a long way, but are you ready for the task I require?]",
        leader_last: "[\"Get out of here!\"]",
        nemesis_first: "[\"Your destruction should make for good sport.\"]",
        nemesis_next: "[\"Your soul shall soon be mine to command.\"]",
        offeredit: "[Take %o with you in your quest for the Amulet.]",
        offeredit2: "[Keep %o, return through the portal to %Z; find the other Amulet.]",
    },
    common: {
        banished: "[You are banished from %H for betraying your allegiance to %d.]",
        legacy: "[%dC has chosen you to recover the Amulet of Yendor for %dI.]",
        pauper_legacy: "[%dC has chosen you to recover the Amulet of Yendor for %dI.]",
    },
};
