// version.js — Build version info
import { game } from './gstate.js';
import { rn2 } from './rng.js';

export const VERSION = '0.1.0';
export const BUILD_DATE = '2026-04-18';
export const COMMIT = 'contest-skeleton';
export const COMMIT_NUMBER = '0';
export const TELEPORT_BUILD_DATE = '2026-04-18';

// C ref: version.c doextversion() — the "About NetHack (version information)"
// help choice ('?a', also the 'V' command).  It creates an NHW_TEXT window and
// writes: the outdented program-name/version/build line, then dat/options
// (OPTIONS_USED) with the makedefs-prefixed lines stripped and outdented
// section headers separated by a blank line, then the runtime info from
// do_runtime_info() — the windowing system, the sound library, and the Lua
// interpreter version + copyright (which for Lua 5.4 embeds the MIT license
// text).  All of this is build-time constant (independent of seed / game
// state), so the faithful port reproduces the exact line set this build emits
// and pages it through the standard full-screen text-window pager.  See
// win/tty/wintty.c process_text_window() for the pagination (23 lines/page,
// "--More--" on every page).
export const VERSION_INFO_LINES = [
    'MacOS NetHack Version 5.0.0 - last build May  2 2026 12:00:00.',
    '',
    'Options compiled into this edition:',
    '    I32LP64 data model, color, data file compression, deferred handling of',
    '    hangup signal, insurance files for recovering from crashes, live logging',
    '    support, log file, extended log file, errors and warnings log file, mail',
    '    daemon, news file, internal pager used for viewing help files, pattern',
    '    matching via posixregex, pseudo random numbers generated by ISAAC64,',
    '    strong PRNG seed from /dev/random, restore saved games via menu, screen',
    '    clipping, shell command, traditional status display, status via',
    '    windowport with highlighting, suspend command, terminal info library,',
    '    system configuration at run-time, show stack trace on error, launch',
    '    browser to report issues, save and bones files accepted from version',
    '    5.0.0 only, and basic NetHack features.',
    '',
    'Supported windowing system:',
    '    "tty" (traditional text with optional line-drawing).',
    '',
    'Supported soundlib:',
    '    "nosound".',
    '',
    "NetHack 5.0.* uses the 'Lua' interpreter to process some data:",
    '    Lua 5.4.8  Copyright (C) 1994-2025 Lua.org, PUC-Rio',
    '    "Permission is hereby granted, free of charge, to any person obtaining',
    '     a copy of this software and associated documentation files (the',
    '     "Software"), to deal in the Software without restriction including',
    '     without limitation the rights to use, copy, modify, merge, publish,',
    '     distribute, sublicense, and/or sell copies of the Software, and to',
    '     permit persons to whom the Software is furnished to do so, subject to',
    '     the following conditions:',
    '     The above copyright notice and this permission notice shall be',
    '     included in all copies or substantial portions of the Software."',
];

// C ref: nhlua.c get_lua_version() — the first time any code needs the Lua
// interpreter's version/copyright text (insert_rtoption() while paging the
// version-info lines), it lazily creates a Lua state via nhl_init(), which
// loads nhlib.lua; that file's top-level `align = {...}; shuffle(align)`
// draws rn2(3) then rn2(2).  get_lua_version() caches the result in a
// process-global (gl.lua_ver), so this only happens once per game.
function ensure_lua_version_loaded() {
    if (game.luaVersionCached) return;
    game.luaVersionCached = true;
    rn2(3); rn2(2); // nhlib.lua top-level shuffle(align)
}

// C ref: version.c doextversion().  Displays the version-info text window.
// Returns ECMD_OK (no game time).  Delegated to the shared full-screen text
// pager in pager.js (dynamic import avoids a load-time cycle between the two
// modules).
export async function doextversion() {
    ensure_lua_version_loaded();
    const { display_text_window } = await import('./pager.js');
    await display_text_window(VERSION_INFO_LINES);
    return 0; // ECMD_OK
}

// ═════════════════════════════════════════════════════════════════════════
// src/version.c — the rest of the file.
//
// INERT: nothing above this line calls anything below it.  Everything here is
// build-time constant or save-file plumbing, so none of it consumes RNG (the
// one exception is insert_rtoption(), which reaches C's get_lua_version() and
// therefore the nhlib.lua top-level shuffle — see ensure_lua_version_loaded()
// above, which this file already models).
//
// Out-parameter convention: C's `char *buf` fill-and-return-buf functions
// return the string here and ignore the buffer argument; C's `int *`/`long *`
// out-parameters are modelled as objects with a `.value` field.
// ═════════════════════════════════════════════════════════════════════════

import {
    nomakedefs, runtime_info_init, release_runtime_info, mdlib_version_string,
    VERSION_MAJOR, VERSION_MINOR, PATCHLEVEL,
} from './mdlib.js';

/* include/global.h BUFSZ */
const BUFSZ = 256;
/* include/hack.h ECMD_OK */
const ECMD_OK = 0;
/* include/flag.h:99-101 */
const VI_NUMBER = 1, VI_NAME = 2, VI_BRANCH = 4;
/* include/hack.h:892-897 uptodate() flags */
const UTD_CHECKSIZES = 0x01, UTD_CHECKFIELDCOUNTS = 0x02,
      UTD_SKIP_SANITY1 = 0x04, UTD_SKIP_SAVEFILEINFO = 0x08,
      UTD_WITHOUT_WAITSYNCH_PERFILE = 0x10, UTD_QUIETLY = 0x20;
/* include/hack.h:900-909 uptodate()/compare_critical_bytes() return codes */
const SF_UPTODATE = 0, SF_OUTDATED = 1,
      SF_CRITICAL_BYTE_COUNT_MISMATCH = 2,
      SF_DM_IL32LLP64_ON_ILP32LL64 = 3, SF_DM_I32LP64_ON_ILP32LL64 = 4,
      SF_DM_ILP32LL64_ON_I32LP64 = 5, SF_DM_ILP32LL64_ON_IL32LLP64 = 6,
      SF_DM_I32LP64_ON_IL32LLP64 = 7, SF_DM_IL32LLP64_ON_I32LP64 = 8,
      SF_DM_MISMATCH = 9;
/* include/hack.h:964-972 NHFILE mode bits */
const COUNTING = 1, WRITING = 2, FREEING = 8;
/* include/hack.h:977 enum sf_fnidx */
const exportascii = 2;
/* include/hack.h SFCTOOL_BIT */
const SFCTOOL_BIT = 0x80000000;

/* ── build/environment constants (docs/recording-environment.md) ──
 * sys/share/posixregex.c:52 `const char regex_id[] = "posixregex"` — this
 * build links posixregex, which is why the compiled-options list reads
 * "pattern matching via posixregex".
 */
const regex_id = 'posixregex';
/* src/nhlua.c get_lua_version(): gl.lua_ver comes from LUA_RELEASE with the
   "Lua" prefix stripped, gl.lua_copyright is LUA_COPYRIGHT verbatim. */
const LUA_VER = '5.4.8';
const LUA_COPYRIGHT = 'Lua 5.4.8  Copyright (C) 1994-2025 Lua.org, PUC-Rio';
/* sys/unix/unixmain.c sets gh.hname from argv[0]; the recorder invokes the
   binary as "nethack" (js/topten.js already assumes the same fallback). */
const HNAME_DEFAULT = 'nethack';

// C ref: hacklib.c eos(s) / files.c nh_basename(fname, keep_suffix).
function nh_basename(fname, keep_suffix) {
    if (!fname) return '';
    let p = fname.lastIndexOf('/');
    if (p >= 0) fname = fname.slice(p + 1);
    p = fname.lastIndexOf('.');
    if (p >= 0 && !keep_suffix) fname = fname.slice(0, p);
    return fname;
}

// C ref: version.c:22 version_string(buf, bufsz) — the SHORT "x.y.z" form.
// The mdlib_version_string() fallback exists for paniclog entries written after
// release_runtime_info() has dropped the 'nomakedefs' strings.
export function version_string(buf, bufsz) {
    void buf; void bufsz;
    return (nomakedefs.version_string && nomakedefs.version_string[0])
        ? nomakedefs.version_string
        : mdlib_version_string(buf, '.');
}

// C ref: version.c:35 getversionstring(buf, bufsz) — nomakedefs.version_id plus
// a parenthesised list of whatever git/port info the build has.  For this build
// git_sha/git_branch/git_prefix are all NULL and RUNTIME_PORT_ID is undefined,
// so c stays 0, the " (" is stripped back off and the trailing '.' is restored.
export function getversionstring(buf, bufsz) {
    void buf; void bufsz;
    let out = String(nomakedefs.version_id ?? '');

    {
        let c = 0;
        const dotoff = out.length > 0 && out[out.length - 1] === '.';

        if (dotoff) out = out.slice(0, -1);   /* --p past the '.' */
        const p = out.length;                 /* index of the " (" we add */
        out += ' (';
        /* RUNTIME_PORT_ID: get_port_id() is not compiled in for this build */
        if (nomakedefs.git_sha)
            out += `${c++ ? ',' : ''}${nomakedefs.git_sha}`;
        /* NH_DEVEL_STATUS == NH_STATUS_RELEASED, so the branch arm is out */
        if (nomakedefs.git_prefix)
            out += `${c++ ? ',' : ''}prefix:${nomakedefs.git_prefix}`;
        if (c)
            out += ')';
        else /* if nothing has been added, strip " (" back off */
            out = out.slice(0, p);
        if (dotoff)
            out += '.';
    }
    return out;
}

// C ref: version.c:89 status_version(buf, bufsz, indent) — the 'showvers'
// status-line text: game name and/or branch name and/or x.y.z, per
// flags.versinfo.  With no git branch, showbranch is forced off.
export function status_version(buf, bufsz, indent) {
    void buf; void bufsz;
    let name = null, altname = null, indentation;
    const vflags = game.flags?.versinfo | 0;
    let shownum = ((vflags & VI_NUMBER) !== 0),
        showname = ((vflags & VI_NAME) !== 0),
        showbranch = ((vflags & VI_BRANCH) !== 0);

    /* game's name {variants should use own name, not "NetHack"} */
    if (showname) {
        /* VERS_GAME_NAME is not defined, so it is basename(gh.hname) */
        name = nh_basename(game.hname ?? HNAME_DEFAULT, false);
        if (!name || !name[0]) /* shouldn't happen */
            showname = false;
    }
    /* git branch name, if available */
    if (showbranch) {
        altname = nomakedefs.git_branch;
        if (!altname || !altname[0])
            showbranch = false;
    }
    if (showname && showbranch) {
        if (altname.slice(0, name.length).toLowerCase() === name.toLowerCase())
            showname = false;
    } else if (!showname && !showbranch) {
        /* flags.versinfo could be set to only 'branch' but it might not
           be available */
        shownum = true;
    }

    let out = '';
    indentation = indent ? ' ' : '';
    if (showname) {
        out += `${indentation}${name}`;
        indentation = ' '; /* forced separator rather than optional indent */
    }
    if (showbranch) {
        out += `${indentation}${altname}`;
        indentation = ' ';
    }
    if (shownum) {
        /* x.y.z version number */
        out += indentation
            + ((nomakedefs.version_string && nomakedefs.version_string[0])
               ? nomakedefs.version_string
               : mdlib_version_string(buf, '.'));
    }
    return out;
}

// C ref: version.c:156 doversion() — the '#versionshort' command; 'm' prefixed
// it becomes the full '#version' display.  Returns ECMD_OK (no game time).
export async function doversion() {
    let buf = '';

    if (game.iflags?.menu_requested)
        return await doextversion();

    const { pline } = await import('./display.js');
    await pline('%s', getversionstring(buf, BUFSZ));
    return ECMD_OK;
}

// C ref: version.c:280 early_version_info(pastebuf) — the `--version` command
// line answer, printed before the window system exists, so it splits the
// " (git info)" tail onto its own line by hand.  RUNTIME_PASTEBUF_SUPPORT is
// not defined for this build.
export async function early_version_info(pastebuf) {
    let buf1 = 'test', buf2, buf;

    /* this is early enough that we have to do our own line-splitting */
    buf1 = getversionstring(buf1, BUFSZ);
    const tmpIdx = buf1.indexOf(' (');  /* split at start of version info */
    if (tmpIdx >= 0) {
        /* retain one buffer so that it all goes into the paste buffer */
        buf2 = `${buf1.slice(0, tmpIdx)}\n${buf1.slice(tmpIdx + 1)}`;
        buf = buf2;
    } else {
        buf = buf1;
    }

    // js/end.js neither defines nor exports raw_printf, so this destructure
    // yielded undefined and the whole `--version` path threw
    // `TypeError: raw_printf is not a function` on every call.  pline.c is its
    // C home and js/pline.js now has it.  Note that pline.js's raw_print() is
    // still a module-local accumulator, as are the copies in js/report.js:42,
    // js/options.js:602 and js/topten.js:335 -- none of the four reaches the
    // tty, so this path is correctly shaped but does not draw.
    const { raw_printf } = await import('./pline.js');
    raw_printf('%s', buf);

    if (pastebuf) {
        raw_printf('%s', 'Paste buffer copy is not available.\n');
    }
}

// C ref: version.c:326 rt_opts[] — tokens makedefs put into dat/options that
// only the running binary can fill in.  gl.lua_ver/gl.lua_copyright are
// populated lazily by get_lua_version().
const rt_opts = [
    { token: ':PATMATCH:', value: () => regex_id },
    { token: ':LUAVERSION:', value: () => (game.luaVersionCached ? LUA_VER : '') },
    { token: ':LUACOPYRIGHT:',
      value: () => (game.luaVersionCached ? LUA_COPYRIGHT : '') },
];

// C ref: version.c:339 insert_rtoption(buf) — substitute every ":TOKEN:" on the
// line; there may be more than one, so the loop does not break on a match.
//
// !gl.lua_ver[0] -> get_lua_version(), which builds a Lua state and therefore
// runs nhlib.lua's top-level shuffle(align): rn2(3) then rn2(2), once per
// process.  ensure_lua_version_loaded() above is that same one-shot.
export function insert_rtoption(buf) {
    let i;

    if (!game.luaVersionCached)
        ensure_lua_version_loaded();

    for (i = 0; i < rt_opts.length; ++i) {
        const val = rt_opts[i].value();
        if (buf.includes(rt_opts[i].token) && val)
            buf = buf.replace(rt_opts[i].token, val);
        /* we don't break out of the loop after a match; there might be
           other matches on the same line */
    }
    return buf;
}

// C ref: version.c:357 comp_times(filetime) — MICRO-only "is this file older
// than the binary?" test.  The comparison is unsigned in C.
export function comp_times(filetime) {
    /* BUILD_TIME is constant but might have L suffix rather than UL;
       'filetime' is historically signed but ought to have been unsigned */
    return (filetime >>> 0) < (nomakedefs.build_time >>> 0);
}

// C ref: version.c:374 check_version(version_data, filename, complain,
// utdflags) — compare a save/bones file's three version words against ours.
// VERSION_COMPATIBILITY is undefined for this build, so the incarnation must
// match exactly.
export async function check_version(version_data, filename, complain, utdflags) {
    if (!filename) {
        complain = false; /* 'complain' requires 'filename' for pline("%s") */
    }
    if ((version_data.feature_set & SFCTOOL_BIT) !== 0) {
        game.converted_savefile_loaded = true;
        version_data.feature_set &= ~SFCTOOL_BIT;
    }
    if (version_data.incarnation !== nomakedefs.version_number) {
        if (complain) {
            const { pline } = await import('./display.js');
            await pline(`Version mismatch for file "${filename}".`);
        }
        return false;
    } else if (
        ((version_data.feature_set & ~nomakedefs.ignored_features) >>> 0)
            !== ((nomakedefs.version_features & ~nomakedefs.ignored_features) >>> 0)
        || (((utdflags & UTD_SKIP_SANITY1) === 0)
             && version_data.entity_count !== nomakedefs.version_sanity1)
        ) {
        if (complain) {
            const { pline } = await import('./display.js');
            await pline(`Configuration incompatibility for file "${filename}".`);
        }
        return false;
    }
    return true;
}

// C ref: version.c:464 get_current_feature_ver() — FEATURE_NOTICE_VER of the
// running binary, used to reject a 'suppress_alert' newer than we are.
// hack.h:1504 FEATURE_NOTICE_VER(maj,min,patch).
export function get_current_feature_ver() {
    return (((VERSION_MAJOR << 24) | (VERSION_MINOR << 16)
             | (PATCHLEVEL << 8) | 0) >>> 0);
}

// C ref: version.c:494 dump_version_info() — the `--dumpversion` answer that
// argcheck() prints and exits on: program name plus the three save-file words
// in hex.  Snprintf's "%-12.33s" left-justifies to 12 and truncates at 33.
export async function dump_version_info() {
    let hname = game.hname ? game.hname : 'nethack';

    if (hname.length > 33)
        hname = hname.slice(hname.length - 33);
    runtime_info_init();
    const hex8 = (n) => (n >>> 0).toString(16).padStart(8, '0');
    /* version_sanity1 exceeds 32 bits, so format it without the >>> 0 clamp */
    const hexN = (n) => Math.trunc(n).toString(16).padStart(8, '0');
    const buf = `${hname.slice(0, 33).padEnd(12, ' ')} `
        + `${hexN(nomakedefs.version_number)} `
        + `${hex8(nomakedefs.version_features & ~nomakedefs.ignored_features)} `
        + `${hexN(nomakedefs.version_sanity1)}`;
    const { raw_print } = await import('./end.js');
    raw_print(buf);
    release_runtime_info();
    return;
}

// C ref: version.c:512 store_version(nhfp) — the first thing written to any
// save/bones/level file: the critical-size bytes then the version_info struct,
// both outside the buffered-write window.  js/storage.js is frozen and owns its
// own format, so Sfo_version_info() just appends the record to nhfp.
export function store_version(nhfp) {
    const version_data = { incarnation: 0, feature_set: 0, entity_count: 0 };

    /* actual version number */
    version_data.incarnation = nomakedefs.version_number;
    /* bitmask of config settings */
    version_data.feature_set = nomakedefs.version_features;
    /* # of monsters and objects */
    version_data.entity_count = nomakedefs.version_sanity1;

    /* bwrite() before bufon() uses plain write() */
    if (nhfp?.structlevel) bufoff(nhfp.fd);

    store_critical_bytes(nhfp);
    Sfo_version_info(nhfp, version_data, 'version_info');

    if (nhfp?.structlevel) bufon(nhfp.fd);
    return;
}

// C ref: version.c:546 critical_sizes[] — sizeof() of every type a save file
// encodes, so a file written by a differently-compiled binary is rejected
// before it is parsed.  SF_INCLUDE_SUBSTRUCTS is NOT defined for this build,
// so the substructure block is absent and SIZE(critical_sizes) is 80.
//
// The scalar sizes below follow from the I32LP64 data model plus the typedefs
// (config.h schar/uchar, global.h coordxy/xint16/xint8/boolean, integer.h).
// C's sizeof of a STRUCT has no JavaScript counterpart — padding and field
// order are the compiler's — so those entries carry `null` rather than a
// guess.  Only get_critical_size_count() (the array LENGTH) is meaningful
// today; a real compare_critical_bytes() would need them filled in from the
// recorder binary.
const critical_sizes = [
    { ucsize: 0, nm: 'unused' },
    /* simple types, that don't have subfields */
    { ucsize: 2, nm: 'short' },
    { ucsize: 4, nm: 'int' },
    { ucsize: 8, nm: 'long' },
    { ucsize: 8, nm: 'long long' },
    { ucsize: 8, nm: 'genericptr_t' },
    { ucsize: 1, nm: 'aligntyp' },          /* align.h: typedef schar */
    { ucsize: 1, nm: 'boolean' },           /* global.h: unsigned char */
    { ucsize: 2, nm: 'coordxy' },           /* global.h: int16_t */
    { ucsize: 2, nm: 'int16' },
    { ucsize: 4, nm: 'int32' },
    { ucsize: 8, nm: 'int64' },
    { ucsize: 1, nm: 'schar' },
    { ucsize: 8, nm: 'size_t' },
    { ucsize: 1, nm: 'uchar' },
    { ucsize: 2, nm: 'uint16' },
    { ucsize: 4, nm: 'uint32' },
    { ucsize: 8, nm: 'uint64' },
    { ucsize: 8, nm: 'ulong' },
    { ucsize: 4, nm: 'unsigned' },
    { ucsize: 2, nm: 'ushort' },
    { ucsize: 2, nm: 'xint16' },            /* global.h: int16_t */
    { ucsize: 1, nm: 'xint8' },             /* global.h: int8_t */
    /* complex - they break down into one or more simple types */
    { ucsize: null, nm: 'struct arti_info' },
    { ucsize: null, nm: 'struct nhrect' },
    { ucsize: null, nm: 'struct branch' },
    { ucsize: null, nm: 'struct bubble' },
    { ucsize: null, nm: 'struct cemetery' },
    { ucsize: null, nm: 'struct context_info' },
    { ucsize: null, nm: 'struct nhcoord' },
    { ucsize: null, nm: 'struct damage' },
    { ucsize: null, nm: 'struct dest_area' },
    { ucsize: null, nm: 'struct dgn_topology' },
    { ucsize: null, nm: 'struct dungeon' },
    { ucsize: null, nm: 'struct d_level' },
    { ucsize: null, nm: 'struct ebones' },
    { ucsize: null, nm: 'struct edog' },
    { ucsize: null, nm: 'struct egd' },
    { ucsize: null, nm: 'struct emin' },
    { ucsize: null, nm: 'struct engr' },
    { ucsize: null, nm: 'struct epri' },
    { ucsize: null, nm: 'struct eshk' },
    { ucsize: null, nm: 'struct fe' },
    { ucsize: null, nm: 'struct flag' },
    { ucsize: null, nm: 'struct fruit' },
    { ucsize: null, nm: 'struct gamelog_line' },
    { ucsize: null, nm: 'struct kinfo' },
    { ucsize: null, nm: 'struct levelflags' },
    { ucsize: null, nm: 'struct ls_t' },
    { ucsize: null, nm: 'struct linfo' },
    { ucsize: null, nm: 'struct mapseen_feat' },
    { ucsize: null, nm: 'struct mapseen_flags' },
    { ucsize: null, nm: 'struct mapseen_rooms' },
    { ucsize: null, nm: 'struct mextra' },
    { ucsize: null, nm: 'struct mkroom' },
    { ucsize: null, nm: 'struct monst' },
    { ucsize: null, nm: 'struct mvitals' },
    { ucsize: null, nm: 'struct obj' },
    { ucsize: null, nm: 'struct objclass' },
    { ucsize: null, nm: 'struct oextra' },
    { ucsize: null, nm: 'struct q_score' },
    { ucsize: null, nm: 'struct rm' },
    { ucsize: null, nm: 'struct spell' },
    { ucsize: null, nm: 'struct stairway' },
    { ucsize: null, nm: 'struct s_level' },
    { ucsize: null, nm: 'struct trap' },
    { ucsize: null, nm: 'struct version_info' },
    { ucsize: null, nm: 'anything' },
    /* struct you requires 2 bytes */
    { ucsize: null, nm: 'you_LO' },
    { ucsize: null, nm: 'you_HI' },
    /* SF_INCLUDE_SUBSTRUCTS is not defined for this build */
    /* 10 for future expansion without changing array size */
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
    { ucsize: 0, nm: '' },
];

// C ref: version.c:666 `uchar cscbuf[SIZE(critical_sizes)]`.
const cscbuf = new Array(critical_sizes.length).fill(0);

// C ref: version.c:669 get_critical_size_count().
export function get_critical_size_count() {
    return critical_sizes.length;
}

// C ref: version.c:676 store_critical_bytes(nhfp) — a format indicator, the
// count, then one byte per critical size.  Only on a WRITING pass.
export function store_critical_bytes(nhfp) {
    let i, cnt;
    let indicate = 'u';
    const csc_count = critical_sizes.length;

    if ((nhfp?.mode | 0) & WRITING) {
        indicate = (nhfp.structlevel) ? 'h'
                 : (nhfp.fnidx === exportascii) ? 'a'
                 : '?';
        Sfo_char(nhfp, indicate, 'indicate-format', 1);
        Sfo_char(nhfp, csc_count, 'count-critical_sizes', 1);
        cnt = csc_count;
        for (i = 0; i < cnt; ++i) {
            Sfo_uchar(nhfp, critical_sizes[i].ucsize, 'critical_sizes');
        }
    }
}

// C ref: version.c:713 uptodate(nhfp, name, utdflags) — read the critical bytes
// and the version_info struct off the front of a file and decide whether this
// binary can read the rest.  See the SF_* table for the return codes.
export async function uptodate(nhfp, name, utdflags) {
    const vers_info = { incarnation: 0, feature_set: 0, entity_count: 0 };
    let indicator;
    let sfstatus = 0;
    const idx_1st_mismatch = { value: 0 };
    const quietly = (utdflags & UTD_QUIETLY) !== 0;
    const verbose = name ? true : false;

    indicator = Sfi_char(nhfp, 'indicate-format', 1);
    void indicator;
    if ((sfstatus = compare_critical_bytes(nhfp, idx_1st_mismatch, utdflags))
                                                            !== SF_UPTODATE) {
        if (sfstatus > 0 && idx_1st_mismatch.value) {
            if (!quietly)
                raw_printf_local(
                    `comparison of critical bytes mismatched at `
                    + `${critical_sizes[idx_1st_mismatch.value].ucsize} `
                    + `(${critical_sizes[idx_1st_mismatch.value].nm}).`);
        }
    }

    Sfi_version_info(nhfp, vers_info, 'version_info');
    if (!(await check_version(vers_info, name, verbose, utdflags))) {
        if (verbose) {
            if ((utdflags & UTD_WITHOUT_WAITSYNCH_PERFILE) === 0) {
                wait_synch_local();
            }
        }
        return SF_OUTDATED;
    }
    return sfstatus;
}

// C ref: version.c:763 compare_critical_bytes(nhfp, idx_1st_mismatch, utdflags)
// — byte-for-byte compare of the file's sizeof table against ours, naming the
// data-model pair when the first five (short/int/long/long long/ptr) explain it.
export function compare_critical_bytes(nhfp, idx_1st_mismatch, utdflags) {
    const active_csc_count = critical_sizes.length;
    let file_csc_count;
    let i, cnt = active_csc_count, dmmismatch = SF_DM_MISMATCH;
    const quietly = (utdflags & UTD_QUIETLY) !== 0;

    file_csc_count = Sfi_char(nhfp, 'count-critical_sizes', 1);
    if (file_csc_count > cnt) {
        if (!quietly)
            raw_printf_local('critical byte counts do not match'
                             + `, file:${file_csc_count}`
                             + `, critical_sizes:${critical_sizes.length}.`);
        return SF_CRITICAL_BYTE_COUNT_MISMATCH;
    }
    for (i = 0; i < file_csc_count; ++i) {
        cscbuf[i] = Sfi_uchar(nhfp, 'critical_sizes');
    }
    for (i = 1; i < cnt; ++i) {
        if (cscbuf[i] !== critical_sizes[i].ucsize) {
            const dm = datamodel(0);
            const dmfile = what_datamodel_is_this(0,
                                                  cscbuf[1],  /* short */
                                                  cscbuf[2],  /* int */
                                                  cscbuf[3],  /* long */
                                                  cscbuf[4],  /* long long */
                                                  cscbuf[5]); /* ptr */

            if (dmfile === 'IL32LLP64' && dm === 'ILP32LL64') {
                /*  Windows x64 savefile on x86 */
                dmmismatch = SF_DM_IL32LLP64_ON_ILP32LL64;
            } else if (dmfile === 'I32LP64' && dm === 'ILP32LL64') {
                /* Unix 64 savefile on x86*/
                dmmismatch = SF_DM_I32LP64_ON_ILP32LL64;
            } else if (dmfile === 'ILP32LL64' && dm === 'I32LP64') {
                /*  x86 savefile on Unix 64 */
                dmmismatch = SF_DM_ILP32LL64_ON_I32LP64;
            } else if (dmfile === 'ILP32LL64' && dm === 'IL32LLP64') {
                /* x86 savefile on Windows x64 */
                dmmismatch = SF_DM_ILP32LL64_ON_IL32LLP64;
            } else if (dmfile === 'I32LP64' && dm === 'IL32LLP64') {
                /* Unix 64 savefile on Windows x64 */
                dmmismatch = SF_DM_I32LP64_ON_IL32LLP64;
            } else if (dmfile === 'IL32LLP64' && dm === 'I32LP64') {
                /* Windows x64 savefile on Unix 64 */
                dmmismatch = SF_DM_IL32LLP64_ON_I32LP64;
            }
            if (idx_1st_mismatch)
                idx_1st_mismatch.value = i;
            return dmmismatch;
        }
    }
    return SF_UPTODATE; /* everything matched */
}

// C ref: version.c:840 validate(nhfp, name, without_waitsynch_perfile) — the
// wrapper every file-open path uses; it derives utdflags from how the file is
// marshalled (struct-level vs field-level) and calls uptodate().
export async function validate(nhfp, name, without_waitsynch_perfile) {
    let utdflags = 0;
    let validsf = 0;

    if (nhfp?.structlevel) utdflags |= UTD_CHECKSIZES;
    if (without_waitsynch_perfile) utdflags |= UTD_WITHOUT_WAITSYNCH_PERFILE;
    if (nhfp?.fieldlevel) utdflags |= UTD_CHECKFIELDCOUNTS | UTD_SKIP_SANITY1;
    validsf = await uptodate(nhfp, name, utdflags);
    return validsf;
}

// ── local stand-ins for collaborators outside this file ──
// hacklib.c datamodel(0) / what_datamodel_is_this(): the recorder's build is
// I32LP64 (short 2, int 4, long 8, long long 8, ptr 8).
const DM_TABLE = [
    { sz: [2, 4, 4, 8, 4], datamodel: 'ILP32LL64', dmplatform: 'x86 32-bit' },
    { sz: [2, 4, 4, 8, 8], datamodel: 'IL32LLP64', dmplatform: 'Windows x64 64-bit' },
    { sz: [2, 4, 8, 8, 8], datamodel: 'I32LP64', dmplatform: 'Unix 64-bit' },
    { sz: [2, 8, 8, 8, 8], datamodel: 'ILP64', dmplatform: 'Unix ILP64' },
];
function datamodel(retidx) {
    return what_datamodel_is_this(retidx, 2, 4, 8, 8, 8);
}
function what_datamodel_is_this(retidx, szshort, szint, szlong, szll, szptr) {
    for (const e of DM_TABLE)
        if (szshort === e.sz[0] && szint === e.sz[1] && szlong === e.sz[2]
            && szll === e.sz[3] && szptr === e.sz[4])
            return (retidx === 0) ? e.datamodel : e.dmplatform;
    return 'Unknown';
}
// sfbase.c Sfo_/Sfi_ marshalling is coverage-N/A: js/storage.js is frozen and
// owns the save format, so these append to / read from whatever record list the
// caller's nhfp carries.
function Sfo_char(nhfp, val, tag, _len) {
    if (nhfp && Array.isArray(nhfp.records)) nhfp.records.push({ tag, val });
}
function Sfo_uchar(nhfp, val, tag) {
    if (nhfp && Array.isArray(nhfp.records)) nhfp.records.push({ tag, val });
}
function Sfo_version_info(nhfp, vi, tag) {
    if (nhfp && Array.isArray(nhfp.records))
        nhfp.records.push({ tag, val: { ...vi } });
}
function Sfi_char(nhfp, tag, _len) {
    const r = nhfp?.records?.shift();
    return (r && r.tag === tag) ? r.val : 0;
}
function Sfi_uchar(nhfp, tag) {
    const r = nhfp?.records?.shift();
    return (r && r.tag === tag) ? r.val : 0;
}
function Sfi_version_info(nhfp, vi, tag) {
    const r = nhfp?.records?.shift();
    if (r && r.tag === tag && r.val) Object.assign(vi, r.val);
}
// sfstruct.c bufoff()/bufon(): buffered-write control around the version
// header.  js/storage.js does its own buffering, so these are genuine no-ops.
function bufoff(_fd) {}
function bufon(_fd) {}
// hack.h raw_printf()/wait_synch(): uptodate() runs before the window system
// exists on some paths, so C writes straight to stderr.
function raw_printf_local(s) { game._raw_printf = s; }
function wait_synch_local() {}
